# Example Render configuration. You will need to adjust this for the different services you run.
previews:
  generation: manual
  expireAfterDays: 3
services:
  - type: web
    repo: https://github.com/nativeapptemplate/nativeapptemplateapi
    name: nativeapptemplateapi
    plan: standard
    previews:
      plan: starter
    env: ruby
    region: singapore # the region must be consistent across all services for the internal keys to be read
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    initialDeployHook: "./bin/render-seed.sh"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 1
      - key: SOLID_QUEUE_IN_PUMA
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: nativeapptemplateapi
          property: connectionString
      - key: CACHE_DATABASE_URL
        fromDatabase:
          name: nativeapptemplateapi-cache
          property: connectionString
      - key: QUEUE_DATABASE_URL
        fromDatabase:
          name: nativeapptemplateapi-queue
          property: connectionString
      - key: CABLE_DATABASE_URL
        fromDatabase:
          name: nativeapptemplateapi-cable
          property: connectionString
      - fromGroup: nativeapptemplateapi-env

databases:
  - name: nativeapptemplateapi
    plan: basic-256mb
    previewPlan: basic-256mb
    region: singapore # the region must be consistent across all services for the internal keys to be read
    ipAllowList: [] # only allow internal connections
    diskSizeGB: 5

  - name: nativeapptemplateapi-cache
    plan: basic-256mb
    previewPlan: basic-256mb
    region: singapore
    ipAllowList: []

  - name: nativeapptemplateapi-queue
    plan: basic-256mb
    previewPlan: basic-256mb
    region: singapore
    ipAllowList: []

  - name: nativeapptemplateapi-cable
    plan: basic-256mb
    previewPlan: basic-256mb
    region: singapore
    ipAllowList: []
