# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: nativeapptemplateapi_development
  cache:
    <<: *default
    database: nativeapptemplateapi_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: nativeapptemplateapi_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: nativeapptemplateapi_development_cable
    migrations_paths: db/cable_migrate

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: nativeapptemplateapi_test

staging:
  primary: &primary_staging
    <<: *default
    database: nativeapptemplateapi_staging
    username: nativeapptemplateapi
    password: <%= ENV["NATIVEAPPTEMPLATEAPI_DATABASE_PASSWORD"] %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_staging
    database: nativeapptemplateapi_staging_cache
    migrations_paths: db/cache_migrate
    url: <%= ENV["CACHE_DATABASE_URL"] %>
  queue:
    <<: *primary_staging
    database: nativeapptemplateapi_staging_queue
    migrations_paths: db/queue_migrate
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
  cable:
    <<: *primary_staging
    database: nativeapptemplateapi_staging_cable
    migrations_paths: db/cable_migrate
    url: <%= ENV["CABLE_DATABASE_URL"] %>

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
production:
  primary: &primary_production
    <<: *default
    database: nativeapptemplateapi_production
    username: nativeapptemplateapi
    password: <%= ENV['NATIVEAPPTEMPLATEAPI_DATABASE_PASSWORD'] %>
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: nativeapptemplateapi_production_cache
    migrations_paths: db/cache_migrate
    url: <%= ENV["CACHE_DATABASE_URL"] %>
  queue:
    <<: *primary_production
    database: nativeapptemplateapi_production_queue
    migrations_paths: db/queue_migrate
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
  cable:
    <<: *primary_production
    database: nativeapptemplateapi_production_cable
    migrations_paths: db/cable_migrate
    url: <%= ENV["CABLE_DATABASE_URL"] %>
